name: family_routine
description: Family Routine App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^5.4.0
  flutter_secure_storage: ^11.2.0
  go_router: ^13.2.0
  easy_localization: ^3.0.3
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/fonts/LICENSE-lucide.txt
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/fonts/lucide.ttf
