version: '3.8'

services:
  app:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: rust_app
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - RUST_LOG=debug
    depends_on:
      db:
        condition: service_started 
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: